harness:
  truth_data_path: /home/collections5/dynamic-domain-2015/dynamic-domain-2015-truth-data-v2.xml
  run_file_path: output.txt
  topic_ids: []
  batch_size: 5

kvlayer:
  namespace: trec
  app_name: dd
  storage_type: 'local'
