harness:
  truth_data_path: trec-dd-early-version-of-truth-2015.csv
  run_file_path: output.txt
  topic_ids: []
  batch_size: 5

kvlayer:
  namespace: trec
  app_name: dd
  storage_type: postgrest
  postgrest:
    storage_addresses: ['10.0.0.87:5432']
    username: postgres
    password: postgres
    dbname: trec_dd
